### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrei-dracea** [ck-tm/cookiecutter-django-wagtail#1]
- [ ] update cookie consent
- [ ] add generic styling
  - [ ] columns (variable, scrollable on mobile etc.)
  - [ ] 
- [ ] replace npm with yarn in docker 
- [ ] add github actions for CI
- [ ] `.djlint` ignore rules
- [ ]
